insert into STUDENT(email, first_name, last_name, password) VALUES('lukas.konstantin@easylearn.mis.com', 'Lukas', 'Konstantin', '123456')
insert into STUDENT(email, first_name, last_name, password) VALUES('ben.jonas@easylearn.mis.com', 'Ben', 'Jonas', '123456')
insert into STUDENT(email, first_name, last_name, password) VALUES('elias.niklas@easylearn.mis.com', 'Elias', 'Niklas', '123456')
insert into STUDENT(email, first_name, last_name, password) VALUES('david.oskar@easylearn.mis.com', 'David', 'Oskar', '123456')
insert into STUDENT(email, first_name, last_name, password) VALUES('philipp.leon@easylearn.mis.com', 'Philipp', 'Leon', '123456')
insert into STUDENT(email, first_name, last_name, password) VALUES('lucy.konstantin@easylearn.mis.com', 'Lucy', 'Konstantin', '123456')
insert into STUDENT(email, first_name, last_name, password) VALUES('ella.jonas@easylearn.mis.com', 'Ella', 'Jonas', '123456')
insert into STUDENT(email, first_name, last_name, password) VALUES('amy.niklas@easylearn.mis.com', 'Amy', 'Niklas', '123456')
insert into STUDENT(email, first_name, last_name, password) VALUES('emely.oskar@easylearn.mis.com', 'Emely', 'Oskar', '123456')
insert into STUDENT(email, first_name, last_name, password) VALUES('finja.leaon@easylearn.mis.com', 'Finja', 'Leon', '123456')
insert into COURSE(course_code, grade, name, content, description) VALUES('MAT2', 2, 'Mathematics', 'Content of Mathematics for grade 2', 'Content of Mathematics for grade 2')
insert into COURSE(course_code, grade, name, content, description) VALUES('MAT3', 3, 'Mathematics', 'Content of Mathematics for grade 3', 'Content of Mathematics for grade 3')
insert into COURSE(course_code, grade, name, content, description) VALUES('MAT4', 4, 'Mathematics', 'Content of Mathematics for grade 4', 'Content of Mathematics for grade 4')
insert into COURSE(course_code, grade, name, content, description) VALUES('ENG1', 1, 'English', 'Content of English for grade 1', 'Content of English for grade 1')
insert into COURSE(course_code, grade, name, content, description) VALUES('ENG2', 2, 'English', 'Content of English for grade 2', 'Content of English for grade 2')
insert into COURSE(course_code, grade, name, content, description) VALUES('ENG3', 3, 'English', 'Content of English for grade 3', 'Content of English for grade 3')
insert into COURSE(course_code, grade, name, content, description) VALUES('ENG4', 4, 'English', 'Content of English for grade 4', 'Content of English for grade 4')
insert into PARENT(email, first_name, last_name, password, type) VALUES('falko.konstantin@easylearn.mis.com', 'Falko', 'Konstantin', '123456', 'FATHER')
insert into PARENT(email, first_name, last_name, password, type) VALUES('Gabrielle.jonas@easylearn.mis.com', 'Gabrielle', 'Jonas', '123456', 'MOTHER')
insert into PARENT(email, first_name, last_name, password, type) VALUES('Fynn.Niklas@easylearn.mis.com', 'Fynn', 'Niklas', '123456', 'FATHER')
insert into PARENT(email, first_name, last_name, password, type) VALUES('Grit.Oskar@easylearn.mis.com', 'Grit', 'Oskar', '123456', 'MOTHER')
insert into PARENT(email, first_name, last_name, password, type) VALUES('Flavio.Leon@easylearn.mis.com', 'Flavio', 'Leon', '123456', 'FATHER')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 10:00:00', 202, '2019-11-15 08:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 10:00:00', 203, '2019-11-15 08:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 10:00:00', 204, '2019-11-15 08:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 10:00:00', 205, '2019-11-15 08:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 10:00:00', 205, '2019-11-15 08:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 12:00:00', 202, '2019-11-15 10:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 12:00:00', 203, '2019-11-15 10:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 12:00:00', 204, '2019-11-15 10:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 12:00:00', 205, '2019-11-15 10:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 12:00:00', 205, '2019-11-15 10:00:00')
insert into TEACHER(email, first_name, last_name, password) VALUES('Nadja.Marlon@easylearn.mis.com', 'Nadja', 'Marlon', '123456')
insert into TEACHER(email, first_name, last_name, password) VALUES('Nadine.Mark@easylearn.mis.com', 'Nadine', 'Mark', '123456')
insert into TEACHER(email, first_name, last_name, password) VALUES('Matti.Martin@easylearn.mis.com', 'Matti', 'Martin', '123456')
insert into TEACHER(email, first_name, last_name, password) VALUES('Morris.Miran@easylearn.mis.com', 'Morris', 'Miran', '123456')
insert into TEACHER(email, first_name, last_name, password) VALUES('Nancy.Niklas@easylearn.mis.com', 'Nancy', 'Niklas', '123456')

