insert into STUDENT(username, first_name, last_name, password, user_type) VALUES('lukas.konstantin@easylearn.mis.com', 'Lukas', 'Konstantin', '123456', 'STUDENT')
insert into STUDENT(username, first_name, last_name, password, user_type) VALUES('ben.jonas@easylearn.mis.com', 'Ben', 'Jonas', '123456', 'STUDENT')
insert into STUDENT(username, first_name, last_name, password, user_type) VALUES('elias.niklas@easylearn.mis.com', 'Elias', 'Niklas', '123456', 'STUDENT')
insert into STUDENT(username, first_name, last_name, password, user_type) VALUES('david.oskar@easylearn.mis.com', 'David', 'Oskar', '123456', 'STUDENT')
insert into STUDENT(username, first_name, last_name, password, user_type) VALUES('philipp.leon@easylearn.mis.com', 'Philipp', 'Leon', '123456', 'STUDENT')
insert into STUDENT(username, first_name, last_name, password, user_type) VALUES('lucy.konstantin@easylearn.mis.com', 'Lucy', 'Konstantin', '123456', 'STUDENT')
insert into STUDENT(username, first_name, last_name, password, user_type) VALUES('ella.jonas@easylearn.mis.com', 'Ella', 'Jonas', '123456', 'STUDENT')
insert into STUDENT(username, first_name, last_name, password, user_type) VALUES('amy.niklas@easylearn.mis.com', 'Amy', 'Niklas', '123456', 'STUDENT')
insert into STUDENT(username, first_name, last_name, password, user_type) VALUES('emely.oskar@easylearn.mis.com', 'Emely', 'Oskar', '123456', 'STUDENT')
insert into STUDENT(username, first_name, last_name, password, user_type) VALUES('finja.leaon@easylearn.mis.com', 'Finja', 'Leon', '123456', 'STUDENT')
insert into COURSE(course_code, grade, name, content, description) VALUES('MAT2', 2, 'Mathematics', 'Content of Mathematics for grade 2', 'Content of Mathematics for grade 2')
insert into COURSE(course_code, grade, name, content, description) VALUES('MAT3', 3, 'Mathematics', 'Content of Mathematics for grade 3', 'Content of Mathematics for grade 3')
insert into COURSE(course_code, grade, name, content, description) VALUES('MAT4', 4, 'Mathematics', 'Content of Mathematics for grade 4', 'Content of Mathematics for grade 4')
insert into COURSE(course_code, grade, name, content, description) VALUES('ENG1', 1, 'English', 'Content of English for grade 1', 'Content of English for grade 1')
insert into COURSE(course_code, grade, name, content, description) VALUES('ENG2', 2, 'English', 'Content of English for grade 2', 'Content of English for grade 2')
insert into COURSE(course_code, grade, name, content, description) VALUES('ENG3', 3, 'English', 'Content of English for grade 3', 'Content of English for grade 3')
insert into COURSE(course_code, grade, name, content, description) VALUES('ENG4', 4, 'English', 'Content of English for grade 4', 'Content of English for grade 4')
insert into PARENT(username, first_name, last_name, password, type, user_type) VALUES('falko.konstantin@easylearn.mis.com', 'Falko', 'Konstantin', '123456', 'FATHER', 'PARENT')
insert into PARENT(username, first_name, last_name, password, type, user_type) VALUES('gabrielle.jonas@easylearn.mis.com', 'Gabrielle', 'Jonas', '123456', 'MOTHER', 'PARENT')
insert into PARENT(username, first_name, last_name, password, type, user_type) VALUES('fynn.niklas@easylearn.mis.com', 'Fynn', 'Niklas', '123456', 'FATHER', 'PARENT')
insert into PARENT(username, first_name, last_name, password, type, user_type) VALUES('grit.oskar@easylearn.mis.com', 'Grit', 'Oskar', '123456', 'MOTHER', 'PARENT')
insert into PARENT(username, first_name, last_name, password, type, user_type) VALUES('flavio.leon@easylearn.mis.com', 'Flavio', 'Leon', '123456', 'FATHER', 'PARENT')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 10:00:00', 202, '2019-11-15 08:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 10:00:00', 203, '2019-11-15 08:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 10:00:00', 204, '2019-11-15 08:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 10:00:00', 205, '2019-11-15 08:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 10:00:00', 205, '2019-11-15 08:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 12:00:00', 202, '2019-11-15 10:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 12:00:00', 203, '2019-11-15 10:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 12:00:00', 204, '2019-11-15 10:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 12:00:00', 205, '2019-11-15 10:00:00')
insert into APPOINTMENT(end_date, room_number, start_date) VALUES('2019-11-15 12:00:00', 205, '2019-11-15 10:00:00')
insert into TEACHER(username, first_name, last_name, password, user_type) VALUES('nadja.marlon@easylearn.mis.com', 'Nadja', 'Marlon', '123456', 'TEACHER')
insert into TEACHER(username, first_name, last_name, password, user_type) VALUES('nadine.mark@easylearn.mis.com', 'Nadine', 'Mark', '123456', 'TEACHER')
insert into TEACHER(username, first_name, last_name, password, user_type) VALUES('matti.martin@easylearn.mis.com', 'Matti', 'Martin', '123456', 'TEACHER')
insert into TEACHER(username, first_name, last_name, password, user_type) VALUES('morris.miran@easylearn.mis.com', 'Morris', 'Miran', '123456', 'TEACHER')
insert into TEACHER(username, first_name, last_name, password, user_type) VALUES('nancy.niklas@easylearn.mis.com', 'Nancy', 'Niklas', '123456', 'TEACHER')


